import pandas as pd
df=pd.read_csv("Toyota.csv")
print(df.info())
print(df.head())
print(df.tail())
print(df.shape)
print(df.columns)
print("Data before Cleaning:")
print(df.isna().sum().sum())
df['Age']=df['Age'].fillna(df['Age'].mean())
print("Data after Cleaning:")
#df['KM']=df['KM'].fillna(df['KM'].mean())
df['FuelType']=df['FuelType'].fillna(df['FuelType'].value_counts().index[0])
df['MetColor']=df['MetColor'].fillna(df['MetColor'].mode()[0])
#df['HP']=df['HP'].fillna(df['HP'].median())
print(df.isna().sum().sum())
print(df.info())
