#Part-b Lab 2 (a)
import numpy as np
arr=np.array([10,20,40,50,60,70])
print("Array:")
print(arr)
print("Reshap arrray:\n",arr.reshape(2,3))
arr=np.append(arr,[80,90])
print("Array after append:\n",arr)
arr=np.insert(arr,2,[30])
print("Array after insert:\n",arr)
print("Index of 50:",np.where(arr==50)[0])
print("Maximum in array",np.max(arr))
print("Minimum in array",np.min(arr))
print("Split array:",np.array_split(arr,2))
ar1=np.array([5,3,7,4,9,1,0])
print("Array sorted:",np.sort(ar1))
print("Array index sort:",np.argsort(ar1))
ar2=np.array([[10,20,30],[40,50,60]])
print("2-D Array:\n",ar2)
print("Horizontal split:\n",np.hsplit(ar2,3))
print("Vertical split:\n",np.vsplit(ar2,2))
